//
//  Constants.swift
//  Mentormee_ver2.0
//
//  Created by Robert D'Ippolito on 2015-07-26.
//  Copyright (c) 2015 Robert D'Ippolito. All rights reserved.
//

import Foundation

#if Staging
    
    let programUpdate = "http://mentormee.info/dbTestConnect/programUpdate.php"
    let Algorithm_filterOnCapacity2 = "http://mentormee.info/dbTestConnect/Algorithm_filterOnCapacity.php"
    let Algorithm_rating = "http://mentormee.info/dbTestConnect/Algorithm_rating.php"
    let Algorithm_rating_PrimaryCapability = "http://mentormee.info/dbTestConnect/Algorithm_rating_PrimaryCapability.php"
    let Algorithm_rating_dataExtract = "http://mentormee.info/dbTestConnect/Algorithm_rating_dataExtract.php"
    let Algorithm_rating_dataExtract2 = "http://mentormee.info/dbTestConnect/Algorithm_rating_dataExtract2.php"
    let Algorithm_rating_dataExtract3 = "http://mentormee.info/dbTestConnect/Algorithm_rating_dataExtract3.php"
    let updatePublicProfileMentee = "http://mentormee.info/dbTestConnect/updatePublicProfileMentee.php"
    let pullMentee3 = "http://mentormee.info/dbTestConnect/pullMentee3.php"
    let pullMenteeInformation = "http://mentormee.info/dbTestConnect/pullMenteeInformation.php"
    let updatePublicProfile3 = "http://mentormee.info/dbTestConnect/updatePublicProfile3.php"
    let universityLookup = "http://mentormee.info/dbTestConnect/universityLookup.php"
    let updateName = "http://mentormee.info/dbTestConnect/updateName.php"
    let updateWhatsup2 = "http://mentormee.info/dbTestConnect/updateWhatsup2.php"
    let updateFacebookID = "http://mentormee.info/dbTestConnect/updateFacebookID.php"
    let updateSkypeID = "http://mentormee.info/dbTestConnect/updateSkypeID.php"
    let updateEmailID = "http://mentormee.info/dbTestConnect/updateEmailID.php"
    let imageUpload4 = "http://mentormee.info/dbTestConnect/imageUpload4.php"
    let populateContractInfo = "http://mentormee.info/dbTestConnect/populateContractInfo.php"
    let genderNameUpdate2 = "http://mentormee.info/dbTestConnect/genderNameUpdate2.php"
    let yearOfStudyUpdate2 = "http://mentormee.info/dbTestConnect/yearOfStudyUpdate2.php"
    let updateUniversityName2 = "http://mentormee.info/dbTestConnect/updateUniversityName2.php"
    let updateFacultyName2 = "http://mentormee.info/dbTestConnect/updateFacultyName2.php"
    let updateProgramName2 = "http://mentormee.info/dbTestConnect/updateProgramName2.php"
    let populateSelectionTable = "http://mentormee.info/dbTestConnect/populateSelectionTable.php"
    let saveUserInfo = "http://mentormee.info/dbTestConnect/saveUserInfo.php"
    let homeScreenUpdate3 = "http://mentormee.info/dbTestConnect/homeScreenUpdate3.php"
    let loginTest = "http://mentormee.info/dbTestConnect/loginTest.php"
    let fetchUserID = "http://mentormee.info/dbTestConnect/fetchUserID.php"
    let signupScript4 = "http://mentormee.info/dbTestConnect/signupScript4.php"
    let fetchUserID2 = "http://mentormee.info/dbTestConnect/fetchUserID2.php"
    let createNewAccount = "http://mentormee.info/dbTestConnect/createNewAccount.php"
    let createPrimaryCapabilityEntry = "http://mentormee.info/dbTestConnect/createPrimaryCapabilityEntry.php"
    let createMessageRecord = "http://mentormee.info/dbTestConnect/createMessageRecord.php"
    let grabEmailFromID = "http://mentormee.info/dbTestConnect/grabEmailFromID.php"
    let MenteeGradYear = "http://mentormee.info/dbTestConnect/MenteeGradYear.php"
    let updateHighSchool = "http://mentormee.info/dbTestConnect/updateHighSchool.php"
    let updateCurrentSituation = "http://mentormee.info/dbTestConnect/updateCurrentSituation.php"
    let updateWhatsupMentee = "http://mentormee.info/dbTestConnect/updateWhatsupMentee.php"
    let updateFutureOptions = "http://mentormee.info/dbTestConnect/updateFutureOptions.php"
    let updateMenteeInterest = "http://mentormee.info/dbTestConnect/updateMenteeInterest.php"
    let populateSelectionTableMentee = "http://mentormee.info/dbTestConnect/populateSelectionTableMentee.php"
    let retrieveMentorID = "http://mentormee.info/dbTestConnect/retrieveMentorID.php"
    let signupScriptMentee = "http://mentormee.info/dbTestConnect/signupScriptMentee.php"
    let fetchUserID3 = "http://mentormee.info/dbTestConnect/fetchUserID3.php"
    let createNewAccountMentee = "http://mentormee.info/dbTestConnect/createNewAccountMentee.php"
    let createMentorshipJoin = "http://mentormee.info/dbTestConnect/createMentorshipJoin.php"
    let fetchCurrentMenteeConnected = "http://mentormee.info/dbTestConnect/fetchCurrentMenteeConnected.php"
    let updateMenteeCount2 = "http://mentormee.info/dbTestConnect/updateMenteeCount2.php"
    
#endif

#if Production
    
    let programUpdate = "http://mentormee.info/dbProduction/programUpdate.php"
    let Algorithm_filterOnCapacity2 = "http://mentormee.info/dbProduction/Algorithm_filterOnCapacity.php"
    let Algorithm_rating = "http://mentormee.info/dbProduction/Algorithm_rating.php"
    let Algorithm_rating_PrimaryCapability = "http://mentormee.info/dbProduction/Algorithm_rating_PrimaryCapability.php"
    let Algorithm_rating_dataExtract = "http://mentormee.info/dbProduction/Algorithm_rating_dataExtract.php"
    let Algorithm_rating_dataExtract2 = "http://mentormee.info/dbProduction/Algorithm_rating_dataExtract2.php"
    let Algorithm_rating_dataExtract3 = "http://mentormee.info/dbProduction/Algorithm_rating_dataExtract3.php"
    let updatePublicProfileMentee = "http://mentormee.info/dbProduction/updatePublicProfileMentee.php"
    let pullMentee3 = "http://mentormee.info/dbProduction/pullMentee3.php"
    let pullMenteeInformation = "http://mentormee.info/dbProduction/pullMenteeInformation.php"
    let updatePublicProfile3 = "http://mentormee.info/dbProduction/updatePublicProfile3.php"
    let universityLookup = "http://mentormee.info/dbProduction/universityLookup.php"
    let updateName = "http://mentormee.info/dbProduction/updateName.php"
    let updateWhatsup2 = "http://mentormee.info/dbProduction/updateWhatsup2.php"
    let updateFacebookID = "http://mentormee.info/dbProduction/updateFacebookID.php"
    let updateSkypeID = "http://mentormee.info/dbProduction/updateSkypeID.php"
    let updateEmailID = "http://mentormee.info/dbProduction/updateEmailID.php"
    let imageUpload4 = "http://mentormee.info/dbProduction/imageUpload4.php"
    let populateContractInfo = "http://mentormee.info/dbProduction/populateContractInfo.php"
    let genderNameUpdate2 = "http://mentormee.info/dbProduction/genderNameUpdate2.php"
    let yearOfStudyUpdate2 = "http://mentormee.info/dbProduction/yearOfStudyUpdate2.php"
    let updateUniversityName2 = "http://mentormee.info/dbProduction/updateUniversityName2.php"
    let updateFacultyName2 = "http://mentormee.info/dbProduction/updateFacultyName2.php"
    let updateProgramName2 = "http://mentormee.info/dbProduction/updateProgramName2.php"
    let populateSelectionTable = "http://mentormee.info/dbProduction/populateSelectionTable.php"
    let saveUserInfo = "http://mentormee.info/dbProduction/saveUserInfo.php"
    let homeScreenUpdate3 = "http://mentormee.info/dbProduction/homeScreenUpdate3.php"
    let loginTest = "http://mentormee.info/dbProduction/loginTest.php"
    let fetchUserID = "http://mentormee.info/dbProduction/fetchUserID.php"
    let signupScript4 = "http://mentormee.info/dbProduction/signupScript4.php"
    let fetchUserID2 = "http://mentormee.info/dbProduction/fetchUserID2.php"
    let createNewAccount = "http://mentormee.info/dbProduction/createNewAccount.php"
    let createPrimaryCapabilityEntry = "http://mentormee.info/dbProduction/createPrimaryCapabilityEntry.php"
    let createMessageRecord = "http://mentormee.info/dbProduction/createMessageRecord.php"
    let grabEmailFromID = "http://mentormee.info/dbProduction/grabEmailFromID.php"
    let MenteeGradYear = "http://mentormee.info/dbProduction/MenteeGradYear.php"
    let updateHighSchool = "http://mentormee.info/dbProduction/updateHighSchool.php"
    let updateCurrentSituation = "http://mentormee.info/dbProduction/updateCurrentSituation.php"
    let updateWhatsupMentee = "http://mentormee.info/dbProduction/updateWhatsupMentee.php"
    let updateFutureOptions = "http://mentormee.info/dbProduction/updateFutureOptions.php"
    let updateMenteeInterest = "http://mentormee.info/dbProduction/updateMenteeInterest.php"
    let populateSelectionTableMentee = "http://mentormee.info/dbProduction/populateSelectionTableMentee.php"
    let retrieveMentorID = "http://mentormee.info/dbProduction/retrieveMentorID.php"
    let signupScriptMentee = "http://mentormee.info/dbProduction/signupScriptMentee.php"
    let fetchUserID3 = "http://mentormee.info/dbProduction/fetchUserID3.php"
    let createNewAccountMentee = "http://mentormee.info/dbProduction/createNewAccountMentee.php"
    let createMentorshipJoin = "http://mentormee.info/dbProduction/createMentorshipJoin.php"
    let fetchCurrentMenteeConnected = "http://mentormee.info/dbProduction/fetchCurrentMenteeConnected.php"
    let updateMenteeCount2 = "http://mentormee.info/dbProduction/updateMenteeCount2.php"
    
#endif

